version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/local/proyectos/PupaSv:/usr/local/proyectos/PupaSv
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - redev

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    user: "1000:1000"  # Ejecución como usuario no root
    ports:
      - "9000:9000"
    networks:
      - redev
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - ./sonarqube_home/conf:/var/sonarqube/conf
      - ./sonarqube_home/data:/var/sonarqube/data
      - ./sonarqube_home/logs:/var/sonarqube/logs
      - ./sonarqube_home/extensions:/var/sonarqube/extensions

volumes:
  jenkins_home:

networks:
  redev:
    driver: bridge
