#!/bin/bash

USER="mjlopez"
API_TOKEN="111c07cf434be23308d143b454ae491fd2"
URL="http://localhost:9080/job/clonar%20git/build?token=tpiTrigger"

response=$(curl --write-out "%{http_code}" --silent --output /dev/null -u $USER:$API_TOKEN "$URL")

if [ "$response" -eq 201 ]; then
    echo "La API respondió con éxito (201). Procediendo con el push."
    exit 0
else
    echo "La API no respondió correctamente. Código HTTP: $response"
    exit 1
fi
